on:
  push: []
  pull_request: []
name: Build-misc

jobs:
  build_9c:
    name: build_lib9c
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
    - run: hooks/pre-commit
    - uses: unsplash/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: |
          @${{ github.actor }} 린트 검사를 통과하지 못했습니다.
          혹시 로컬에서 Git 훅을 설정하지 않으셨나요?
          아래 명령으로 Git 훅 설정을 해주시기 바랍니다.

          ```` bash
          git config core.hooksPath hooks
          ````
      if: failure() && github.event_name == 'pull_request'
    - run: .github/bin/check-libplanet-version.sh
    - uses: unsplash/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: |
          @${{ github.actor }} Libplanet 어셈블리 파일들의 버전이 Lib9c가 참조하는 버전보다 오래되었습니다.
          Lib9c 서브모듈 안에 있는 Libplanet 서브모듈을 `dotnet build` 명령으로 빌드하고 새 어셈블리를 복사하세요.
      if: failure() && github.event_name == 'pull_request'
  build_installer:
    runs-on: windows-latest
    name: build installer
    steps:
      - uses: actions/checkout@v2.3.4
      - run: dotnet publish tools/Updater/Updater/Updater.csproj -r win-x64 --self-contained
      - run: ISCC tools/installer/installer.iss
