on:
  push: []
  pull_request: []
name: Build-misc

jobs:
  build_9c:
    name: build_lib9c
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
    - run: hooks/pre-commit
    - uses: unsplash/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: >
          @${{ github.actor }} Your pull request does not pass lint checks.
          You probably haven't configured hooks in your local Git repository.
          Please configure Git hooks in your local repository using the below
          command:


              git config core.hooksPath hooks
      if: failure() && github.event_name == 'pull_request'
    - run: sudo apt-get install -y exiftool
    - id: clv
      run: .github/bin/check-libplanet-version.sh
    - uses: unsplash/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: >
          @${{ github.actor }} The versions of bundled Libplanet assemblies and
          Libplanet submodule vendored by Lib9c:

          - Libplanet submdoule: ${{ steps.clv.outputs.submodule_version }}

          ${{ join(fromJSON(steps.clv.outputs.unmatches), fromJSON('"\n"')) }}
      if: failure() && github.event_name == 'pull_request'
  build_installer:
    runs-on: windows-latest
    name: build installer
    steps:
      - uses: actions/checkout@v2.3.4
      - run: dotnet publish tools/Updater/Updater/Updater.csproj -r win-x64 --self-contained
      - run: ISCC tools/installer/installer.iss
